<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lalitha A R">
<meta name="author" content="Claude (Anthropic)">
<meta name="dcterms.date" content="2026-03-26">
<meta name="description" content="44 non-INS color variant rows processed → 30 INS colour entries in the clean taxonomy, 7 whole-food colorants deferred. The 7 deferred entries expose a category gap in IFID: substances that function as colorants on Indian labels but have no INS number and no current home in the schema.">

<title>What the colors session resolved, deferred, and left open for the schema</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="track-a.log_files/libs/clipboard/clipboard.min.js"></script>
<script src="track-a.log_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="track-a.log_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="track-a.log_files/libs/quarto-html/popper.min.js"></script>
<script src="track-a.log_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="track-a.log_files/libs/quarto-html/anchor.min.js"></script>
<link href="track-a.log_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="track-a.log_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="track-a.log_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="track-a.log_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="track-a.log_files/libs/bootstrap/bootstrap-2daf5a3bceb9e852f3deb6477265f210.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-this-session-did" id="toc-what-this-session-did" class="nav-link active" data-scroll-target="#what-this-session-did">What this session did</a></li>
  <li><a href="#the-30-ins-colour-entries" id="toc-the-30-ins-colour-entries" class="nav-link" data-scroll-target="#the-30-ins-colour-entries">The 30 INS colour entries</a></li>
  <li><a href="#how-the-37-rows-were-resolved" id="toc-how-the-37-rows-were-resolved" class="nav-link" data-scroll-target="#how-the-37-rows-were-resolved">How the 37 rows were resolved</a>
  <ul class="collapse">
  <li><a href="#pass-1-match-to-existing-ins-25-rows-no-new-entries" id="toc-pass-1-match-to-existing-ins-25-rows-no-new-entries" class="nav-link" data-scroll-target="#pass-1-match-to-existing-ins-25-rows-no-new-entries">Pass 1 — Match to existing INS (25 rows, no new entries)</a></li>
  <li><a href="#pass-2-ins-exists-in-codex-absent-from-taxonomy-6-rows-4-new-entries" id="toc-pass-2-ins-exists-in-codex-absent-from-taxonomy-6-rows-4-new-entries" class="nav-link" data-scroll-target="#pass-2-ins-exists-in-codex-absent-from-taxonomy-6-rows-4-new-entries">Pass 2 — INS exists in Codex, absent from taxonomy (6 rows, 4 new entries)</a></li>
  <li><a href="#pass-3-unresolvable-group-declarations-5-rows-dropped" id="toc-pass-3-unresolvable-group-declarations-5-rows-dropped" class="nav-link" data-scroll-target="#pass-3-unresolvable-group-declarations-5-rows-dropped">Pass 3 — Unresolvable group declarations (5 rows dropped)</a></li>
  <li><a href="#pass-4-ins-absent-from-taxonomy-mineral-source-1-row-1-entry-added" id="toc-pass-4-ins-absent-from-taxonomy-mineral-source-1-row-1-entry-added" class="nav-link" data-scroll-target="#pass-4-ins-absent-from-taxonomy-mineral-source-1-row-1-entry-added">Pass 4 — INS absent from taxonomy, mineral source (1 row, 1 entry added)</a></li>
  </ul></li>
  <li><a href="#the-7-deferred-rows-and-the-schema-gap" id="toc-the-7-deferred-rows-and-the-schema-gap" class="nav-link" data-scroll-target="#the-7-deferred-rows-and-the-schema-gap">The 7 deferred rows and the schema gap</a>
  <ul class="collapse">
  <li><a href="#why-these-were-deferred" id="toc-why-these-were-deferred" class="nav-link" data-scroll-target="#why-these-were-deferred">Why these were deferred</a></li>
  <li><a href="#the-distinction-paprikacarrot-illustrate" id="toc-the-distinction-paprikacarrot-illustrate" class="nav-link" data-scroll-target="#the-distinction-paprikacarrot-illustrate">The distinction paprika/carrot illustrate</a></li>
  </ul></li>
  <li><a href="#regional-naming-kesar-vs-saffron" id="toc-regional-naming-kesar-vs-saffron" class="nav-link" data-scroll-target="#regional-naming-kesar-vs-saffron">Regional naming: kesar vs saffron</a></li>
  <li><a href="#design-question-ins-number-common-name-or-both" id="toc-design-question-ins-number-common-name-or-both" class="nav-link" data-scroll-target="#design-question-ins-number-common-name-or-both">Design question: INS number, common name, or both?</a></li>
  <li><a href="#data-files" id="toc-data-files" class="nav-link" data-scroll-target="#data-files">Data files</a></li>
  <li><a href="#note-on-ai-authorship" id="toc-note-on-ai-authorship" class="nav-link" data-scroll-target="#note-on-ai-authorship">Note on AI authorship</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">What the colors session resolved, deferred, and left open for the schema</h1>
  <div class="quarto-categories">
    <div class="quarto-category">ifid</div>
    <div class="quarto-category">colors</div>
    <div class="quarto-category">data-analysis</div>
    <div class="quarto-category">track-a</div>
  </div>
  </div>

<div>
  <div class="description">
    44 non-INS color variant rows processed → 30 INS colour entries in the clean taxonomy, 7 whole-food colorants deferred. The 7 deferred entries expose a category gap in IFID: substances that function as colorants on Indian labels but have no INS number and no current home in the schema.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Lalitha A R </p>
             <p>Claude (Anthropic) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="what-this-session-did" class="level2">
<h2 class="anchored" data-anchor-id="what-this-session-did">What this session did</h2>
<p>The colors session started from two inputs:</p>
<ul>
<li>25 INS colour entries already in the additives taxonomy, exported to <code>colors_ins_clean.csv</code> as a working reference</li>
<li>44 non-INS colour variant rows from <code>core/all_variants_working.csv</code> — declarations found on Indian labels that had not yet been matched to an INS number</li>
</ul>
<p>Of the 44 variant rows: 37 were resolved and removed from the working file. 5 new INS entries were added to the taxonomy. 7 rows were deferred.</p>
<p>Session close: 2026-03-13.</p>
<hr>
</section>
<section id="the-30-ins-colour-entries" class="level2">
<h2 class="anchored" data-anchor-id="the-30-ins-colour-entries">The 30 INS colour entries</h2>
<p><code>colors_ins_clean.csv</code> holds 30 INS colour entries. This is the reference file for downstream colour resolution work.</p>
<p>Source type distribution across the 30:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>source_type</th>
<th>Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>plant</td>
<td>16</td>
</tr>
<tr class="even">
<td>synthetic</td>
<td>11</td>
</tr>
<tr class="odd">
<td>mineral</td>
<td>3</td>
</tr>
</tbody>
</table>
<p>The INS colour range in Codex runs roughly 100–174. All 30 entries fall within this range, with the exception of INS 152 (Polyethylene glycol, listed as a colour adjunct) and the caramel sub-types (150a, 150c, 150d) which share the 150 base number.</p>
<p>Full list by INS number:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>INS</th>
<th>Official name</th>
<th>source_type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>100</td>
<td>Curcumin</td>
<td>plant</td>
</tr>
<tr class="even">
<td>101(i)</td>
<td>Riboflavin</td>
<td>synthetic</td>
</tr>
<tr class="odd">
<td>102</td>
<td>Tartrazine</td>
<td>synthetic</td>
</tr>
<tr class="even">
<td>110</td>
<td>Sunset yellow FCF, Orange yellow S</td>
<td>synthetic</td>
</tr>
<tr class="odd">
<td>122</td>
<td>Azorubine, Carmoisine</td>
<td>synthetic</td>
</tr>
<tr class="even">
<td>124</td>
<td>Ponceau 4R</td>
<td>synthetic</td>
</tr>
<tr class="odd">
<td>127</td>
<td>Erythrosine</td>
<td>synthetic</td>
</tr>
<tr class="even">
<td>129</td>
<td>Allura Red AC</td>
<td>synthetic</td>
</tr>
<tr class="odd">
<td>132</td>
<td>Indigotine, Indigo carmine</td>
<td>synthetic</td>
</tr>
<tr class="even">
<td>133</td>
<td>Brilliant Blue FCF</td>
<td>synthetic</td>
</tr>
<tr class="odd">
<td>140</td>
<td>Chlorophylls</td>
<td>plant</td>
</tr>
<tr class="even">
<td>141</td>
<td>Copper complexes of chlorophylls</td>
<td>plant</td>
</tr>
<tr class="odd">
<td>150</td>
<td>Caramel</td>
<td>plant</td>
</tr>
<tr class="even">
<td>150a</td>
<td>Plain caramel</td>
<td>plant</td>
</tr>
<tr class="odd">
<td>150c</td>
<td>Ammonia caramel</td>
<td>plant</td>
</tr>
<tr class="even">
<td>150d</td>
<td>Sulphite ammonia caramel</td>
<td>plant</td>
</tr>
<tr class="odd">
<td>152</td>
<td>Polyethylene glycol</td>
<td>synthetic</td>
</tr>
<tr class="even">
<td>160a</td>
<td>Carotenes, mixed</td>
<td>plant</td>
</tr>
<tr class="odd">
<td>160a(i)</td>
<td>Beta-carotene, vegetable</td>
<td>plant</td>
</tr>
<tr class="even">
<td>160b</td>
<td>Annatto extracts</td>
<td>plant</td>
</tr>
<tr class="odd">
<td>160c</td>
<td>Paprika extract</td>
<td>plant</td>
</tr>
<tr class="even">
<td>160d</td>
<td>Lycopene</td>
<td>plant</td>
</tr>
<tr class="odd">
<td>161b</td>
<td>Lutein</td>
<td>plant</td>
</tr>
<tr class="even">
<td>161g</td>
<td>Canthaxanthin</td>
<td>synthetic</td>
</tr>
<tr class="odd">
<td>162</td>
<td>Beetroot Red</td>
<td>plant</td>
</tr>
<tr class="even">
<td>163</td>
<td>Anthocyanins</td>
<td>plant</td>
</tr>
<tr class="odd">
<td>163c</td>
<td>Grape skin extract</td>
<td>plant</td>
</tr>
<tr class="even">
<td>170</td>
<td>Calcium carbonate</td>
<td>mineral</td>
</tr>
<tr class="odd">
<td>171</td>
<td>Titanium dioxide</td>
<td>mineral</td>
</tr>
<tr class="even">
<td>174</td>
<td>Silver</td>
<td>mineral</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="how-the-37-rows-were-resolved" class="level2">
<h2 class="anchored" data-anchor-id="how-the-37-rows-were-resolved">How the 37 rows were resolved</h2>
<section id="pass-1-match-to-existing-ins-25-rows-no-new-entries" class="level3">
<h3 class="anchored" data-anchor-id="pass-1-match-to-existing-ins-25-rows-no-new-entries">Pass 1 — Match to existing INS (25 rows, no new entries)</h3>
<p>25 variant rows mapped to INS entries already in the taxonomy. These included FD&amp;C-named synthetic dyes (e.g.&nbsp;“FD&amp;C Red 40” → INS 129 Allura Red AC) and botanical extract declarations where the INS already existed. No new taxonomy entries were required.</p>
<p>Distribution of resolved variants by INS:</p>
<p>INS 100 (×2), 102 (×2), 110 (×3), 129 (×6), 132 (×2), 133 (×3), 160a(i) (×1), 160b (×3), 160c (×2), 171 (×1).</p>
</section>
<section id="pass-2-ins-exists-in-codex-absent-from-taxonomy-6-rows-4-new-entries" class="level3">
<h3 class="anchored" data-anchor-id="pass-2-ins-exists-in-codex-absent-from-taxonomy-6-rows-4-new-entries">Pass 2 — INS exists in Codex, absent from taxonomy (6 rows, 4 new entries)</h3>
<p>Four entries added: INS 140 (Chlorophylls), 160d (Lycopene), 161b (Lutein), and 150 (Caramel, as a single undifferentiated entry alongside the existing sub-types 150a, 150c, 150d). All four are plant-source entries.</p>
<p>One taxonomy addition not counted here: INS 174 (Silver, mineral) was added in Pass 4 below.</p>
</section>
<section id="pass-3-unresolvable-group-declarations-5-rows-dropped" class="level3">
<h3 class="anchored" data-anchor-id="pass-3-unresolvable-group-declarations-5-rows-dropped">Pass 3 — Unresolvable group declarations (5 rows dropped)</h3>
<p><code>artificial color</code>, <code>artificial colors</code>, <code>synthetic food colors</code>, <code>color vegetable juice</code>, <code>vegetable juice concentrate for color</code> — no single INS number is resolvable from any of these declarations. They were removed from the working file and not added to the taxonomy.</p>
</section>
<section id="pass-4-ins-absent-from-taxonomy-mineral-source-1-row-1-entry-added" class="level3">
<h3 class="anchored" data-anchor-id="pass-4-ins-absent-from-taxonomy-mineral-source-1-row-1-entry-added">Pass 4 — INS absent from taxonomy, mineral source (1 row, 1 entry added)</h3>
<p><code>silver leaf</code> → INS 174 (Silver, mineral). Added to taxonomy.</p>
<hr>
</section>
</section>
<section id="the-7-deferred-rows-and-the-schema-gap" class="level2">
<h2 class="anchored" data-anchor-id="the-7-deferred-rows-and-the-schema-gap">The 7 deferred rows and the schema gap</h2>
<p>7 rows were not resolved to an INS number. They remain in <code>core/all_variants_working.csv</code> with <code>f_revised</code> set to <code>colour|raw_agricultural_material</code>. They will be processed during a raw agricultural material session that has not yet run.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Label text</th>
<th>Source</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kesar</td>
<td>saffron</td>
<td>Hindi name; variant pair with <code>safron</code></td>
</tr>
<tr class="even">
<td>safron</td>
<td>saffron</td>
<td>Spelling variant; variant pair with <code>kesar</code></td>
</tr>
<tr class="odd">
<td>paprika</td>
<td>paprika</td>
<td>Whole dried spice; distinct from INS 160c (solvent-extracted oleoresin)</td>
</tr>
<tr class="even">
<td>hibiscus</td>
<td>hibiscus</td>
<td>Dried flower</td>
</tr>
<tr class="odd">
<td>carrot powder</td>
<td>carrot</td>
<td>Dried whole carrot; distinct from INS 160a(i) beta-carotene extract</td>
</tr>
<tr class="even">
<td>carrot flakes</td>
<td>carrot</td>
<td>Dried whole carrot</td>
</tr>
<tr class="odd">
<td>pomegranate powder</td>
<td>pomegranate</td>
<td>Dried whole fruit powder</td>
</tr>
</tbody>
</table>
<section id="why-these-were-deferred" class="level3">
<h3 class="anchored" data-anchor-id="why-these-were-deferred">Why these were deferred</h3>
<p>Each of these appears on Indian labels as a colour declaration — the product label uses one of these names in the context of declaring colour. None has an INS number. The deferral is not a classification decision; it is an acknowledgement that the current taxonomy structure has no place for them.</p>
<p>These substances share a structural property: they are dried, powdered, or extracted forms of whole food ingredients used for their colouring effect. They are not additives (no INS number, not in the Codex food additives framework). They are not raw ingredients in the conventional IFID sense — they are present on the label as colour declarations, not as primary ingredients.</p>
<p>The <code>raw_agricultural_material</code> lane referenced in their <code>f_revised</code> field does not exist in IFID. It was identified during this session as the correct home for these entries; building that category is a separate task.</p>
</section>
<section id="the-distinction-paprikacarrot-illustrate" class="level3">
<h3 class="anchored" data-anchor-id="the-distinction-paprikacarrot-illustrate">The distinction paprika/carrot illustrate</h3>
<p>INS 160c is “Paprika extract” — a solvent-extracted oleoresin from paprika, with an INS number, classified as a synthetic colour in Codex terms. The paprika row in the deferred set is the whole dried spice ground to a powder.</p>
<p>INS 160a(i) is “Beta-carotene, vegetable” — an extract from carrot. The carrot powder and carrot flakes rows are dried whole carrot.</p>
<p>These are distinct substances with distinct regulatory status. The INS extract has a Codex classification. The whole-food form has no INS number and no Codex colour classification. Both appear on Indian labels as colour declarations. The taxonomy resolves the extract; it cannot resolve the whole-food form.</p>
<hr>
</section>
</section>
<section id="regional-naming-kesar-vs-saffron" class="level2">
<h2 class="anchored" data-anchor-id="regional-naming-kesar-vs-saffron">Regional naming: kesar vs saffron</h2>
<p><code>kesar</code> is the Hindi name for saffron. It appears on Indian labels where an international-market label would say <code>saffron</code>. The two variant rows (<code>kesar</code>, <code>safron</code>) resolve to the same source substance.</p>
<p><code>safron</code> is a spelling variant — not the correct English spelling, not the correct Hindi spelling, but a form found on labels.</p>
<p>This is a labeling normalisation problem, not a taxonomy gap. The deferred entry is not “kesar” as a distinct substance from saffron; it is saffron appearing under its Hindi name. Any IFID matching pipeline processing Indian labels needs to handle regional-language ingredient names alongside English and INS declarations.</p>
<p>The Hindi naming issue is not specific to colours. It is visible here because the colors session processed label text variants directly. The broader implication — that Indian labels use Hindi names for ingredients with no INS number — surfaces as a design question for IFID’s ingredient text matching layer.</p>
<hr>
</section>
<section id="design-question-ins-number-common-name-or-both" class="level2">
<h2 class="anchored" data-anchor-id="design-question-ins-number-common-name-or-both">Design question: INS number, common name, or both?</h2>
<p>The 30 INS colour entries each carry an <code>official_name</code>. For plant-source and synthetic entries, the official name is the Codex GSFA name — which may not be the name on the label.</p>
<p>Examples:</p>
<ul>
<li>INS 129: official name is “Allura Red AC.” Indian labels may say “Allura Red,” “Red 40,” “FD&amp;C Red 40,” or in some cases just “E129” or “INS 129.”</li>
<li>INS 100: official name is “Curcumin.” Indian labels commonly say “turmeric colour” or “हल्दी” (haldi).</li>
<li>INS 160b: official name is “Annatto extracts.” Labels may say “annatto,” “bixin,” “norbixin,” or “natural colour (annatto).”</li>
</ul>
<p>The 25 Pass 1 resolutions were precisely this problem — variant label text mapped to canonical INS entries. The mapping is in <code>core/all_variants_working.csv</code> (resolved rows removed) and in the Pass 1 INS distribution above, but it is not currently captured as a structured alias list in the taxonomy.</p>
<p>Whether IFID displays INS number, official name, common names, or all three for a colour entry is a UI question. Whether IFID stores label text aliases per entry is a schema question. The current taxonomy has the INS number and official name; it does not have a <code>label_aliases</code> or <code>common_names</code> field.</p>
<hr>
</section>
<section id="data-files" class="level2">
<h2 class="anchored" data-anchor-id="data-files">Data files</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>File</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>colors/colors_ins_clean.csv</code></td>
<td>30 INS colour entries; reference for downstream colour resolution</td>
</tr>
<tr class="even">
<td><code>colors/colors_nonins_variants.csv</code></td>
<td>7 deferred whole-food rows; input for raw_agricultural_material session</td>
</tr>
<tr class="odd">
<td><code>colors/cp/README_colors.md</code></td>
<td>Session close notes; full resolution log, taxonomy additions</td>
</tr>
<tr class="even">
<td><code>additives/additives_taxonomy.json</code></td>
<td>Source of truth for all INS entries; updated with 5 additions during this session</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="note-on-ai-authorship" class="level2">
<h2 class="anchored" data-anchor-id="note-on-ai-authorship">Note on AI authorship</h2>
<p>This document was drafted by Claude (Anthropic, Sonnet 4.6) in a Claude Code session on 2026-03-26, from a structured plan written by Lalitha A R.</p>
<p><strong>What Claude did:</strong></p>
<ul>
<li>Queried <code>colors_ins_clean.csv</code> to confirm 30 entries and source type distribution</li>
<li>Identified the 5 entries added in the colors session from the README and confirmed them in the CSV</li>
<li>Read the full session README to verify the four-pass resolution log and deferred row details</li>
<li>Drafted all prose, tables, and section structure</li>
</ul>
<p><strong>Constraints Claude worked under:</strong></p>
<ul>
<li>The paprika/carrot INS-versus-whole-food distinction is drawn from the README notes on the deferred rows; it is not an inference.</li>
<li>The kesar/saffron Hindi naming observation is from the README; the broader implication for IFID’s ingredient text matching is Claude’s synthesis.</li>
<li>The label aliases design question is raised from the Pass 1 data — 25 variant forms mapped to 10 INS numbers — not from the plan.</li>
<li>No claims were made about FSSAI labeling requirements for colour declarations. The absence of a regulatory statement is not an oversight; the session did not produce regulatory data on colour declarations.</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>